name: Jalankan Bot Warung Kiamat

on:
  push:
    branches: [ "main" ]
  schedule:
    # Trik Cron: Server akan otomatis men-trigger/menyalakan ulang bot ini setiap 3 jam
    - cron: '0 */3 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Ambil Code dari Repository
      uses: actions/checkout@v4

    - name: Setup Python di Server GitHub
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Jalankan Bot 24 Jam
      run: python main.py
      env:
        # Mengambil token rahasia dari brankas rahasia GitHub agar tidak diblokir push protection
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}